name: Build and Deploy to Azure Container Apps Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ${{ secrets.REGISTRY_LOGIN_SERVER }}
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
  ACA_ENVIRONMENT: ${{ secrets.ACA_ENVIRONMENT }}

jobs:
  attendance-service:
    runs-on: ubuntu-latest
    name: Build and Deploy Attendance API

    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            attendance:
              - 'Src/Services/AttendanceService/**'

      - if: steps.changes.outputs.attendance == 'true'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - if: steps.changes.outputs.attendance == 'true'
        uses: azure/container-apps-deploy-action@v1
        with:
          dockerfilePath: ./Src/Services/AttendanceService/AttendanceService.Api/AttendanceService.Api/Dockerfile
          appSourcePath: .
          containerAppName: attendance-container
          resourceGroup: ${{ secrets.RESOURCE_GROUP }}
          registryUrl: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registryUsername: ${{ secrets.REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REGISTRY_PASSWORD }}
          containerAppEnvironment: ${{ secrets.ACA_ENVIRONMENT }}
          imageToBuild: ${{ secrets.REGISTRY_LOGIN_SERVER }}/attendance-service:${{ github.sha }}
          ingress: external
          targetPort: 8080

  employee-service:
    runs-on: ubuntu-latest
    name: Build and Deploy Employee API

    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            employee:
              - 'Src/Services/EmployeeService/**'

      - if: steps.changes.outputs.employee == 'true'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - if: steps.changes.outputs.employee == 'true'
        uses: azure/container-apps-deploy-action@v1
        with:
          dockerfilePath: ./Src/Services/EmployeeService/EmployeeService.Api/EmployeeService.Api/Dockerfile
          appSourcePath: .
          containerAppName: employee-container
          resourceGroup: ${{ secrets.RESOURCE_GROUP }}
          registryUrl: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registryUsername: ${{ secrets.REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REGISTRY_PASSWORD }}
          containerAppEnvironment: ${{ secrets.ACA_ENVIRONMENT }}
          imageToBuild: ${{ secrets.REGISTRY_LOGIN_SERVER }}/employee-service:${{ github.sha }}
          ingress: external
          targetPort: 8080
