name: Build and Deploy to Azure Container Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ${{ secrets.REGISTRY_LOGIN_SERVER }}
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
  ACA_ENVIRONMENT: ${{ secrets.ACA_ENVIRONMENT }}

jobs:
  employee-service:
    name: Build and Deploy Employee API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Push Employee API Image to ACR
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: .
          dockerfilePath: ./src/EmployeeService/EmployeeService.Api/Dockerfile
          containerAppName: employee-container
          registryUrl: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registryUsername: ${{ secrets.REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REGISTRY_PASSWORD }}
          resourceGroup: ${{ secrets.RESOURCE_GROUP }}
          imageToBuild: ${{ secrets.REGISTRY_LOGIN_SERVER }}/employee-service:${{ github.sha }}

  attendance-service:
    name: Build and Deploy Attendance API
    runs-on: ubuntu-latest
    needs: employee-service  # optional chaining

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Push Attendance API Image to ACR
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: .
          dockerfilePath: ./src/AttendanceService/AttendanceService.Api/Dockerfile
          containerAppName: attendane-container
          registryUrl: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registryUsername: ${{ secrets.REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REGISTRY_PASSWORD }}
          resourceGroup: ${{ secrets.RESOURCE_GROUP }}
          imageToBuild: ${{ secrets.REGISTRY_LOGIN_SERVER }}/attendance-service:${{ github.sha }}
