name: Deploy EmployeeService

on:
  push:
    paths:
      - 'Src/Services/EmployeeService/**'
      - '.github/workflows/deploy-employee.yml'
  workflow_dispatch:

jobs:
  deploy-employee-service:
    runs-on: ubuntu-latest
    name: Build and Deploy Employee Service

    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/container-apps-deploy-action@v1
        with:
          dockerfilePath: ./Src/Services/EmployeeService/EmployeeService.Api/EmployeeService.Api/Dockerfile
          appSourcePath: .
          containerAppName: employee-container
          resourceGroup: ${{ secrets.RESOURCE_GROUP }}
          registryUrl: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registryUsername: ${{ secrets.REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REGISTRY_PASSWORD }}
          containerAppEnvironment: ${{ secrets.ACA_ENVIRONMENT }}
          imageToBuild: ${{ secrets.REGISTRY_LOGIN_SERVER }}/employee-service:${{ github.sha }}
          ingress: external
          targetPort: 8080
