name: Deploy AttendanceService

on:
  push:
    paths:
      - 'Src/Services/AttendanceService/**'
      - '.github/workflows/deploy-attendance.yml'
  workflow_dispatch:

jobs:
  deploy-attendance-service:
    runs-on: ubuntu-latest
    name: Build and Deploy Attendance Service

    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/container-apps-deploy-action@v1
        with:
          dockerfilePath: ./Src/Services/AttendanceService/AttendanceService.Api/AttendanceService.Api/Dockerfile
          appSourcePath: .
          containerAppName: attendance-container
          resourceGroup: ${{ secrets.RESOURCE_GROUP }}
          registryUrl: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registryUsername: ${{ secrets.REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REGISTRY_PASSWORD }}
          containerAppEnvironment: ${{ secrets.ACA_ENVIRONMENT }}
          imageToBuild: ${{ secrets.REGISTRY_LOGIN_SERVER }}/attendance-service:${{ github.sha }}
          ingress: external
          targetPort: 8080
